# Generated by Django 5.1 on 2024-09-13 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=1000)),
                ('row', models.CharField(max_length=50)),
                ('seat', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('booking_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('film_studio', models.CharField(max_length=80)),
                ('age_category', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=5)),
                ('rating', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovieShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('movie', models.ForeignKey(default='uncommon movie', on_delete=django.db.models.deletion.SET_DEFAULT, to='booking_app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='HallSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.CharField(max_length=50)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking_app.client')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.movieshow')),
            ],
        ),
    ]
